secret_key_base: vdxQqmaap7lSzeL4OhZ5RRnQyE0PzV4bY21poPVPT8s
port: 3000
name: amber-perf-test
logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  skip:
    -
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://emmanuelsw:@localhost:5432/amber_perf_test_test
session:
  key: amber.session
  store: signed_cookie
  expires: 0
smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.


